RCScustomer/Controllers/JobEstimateController.cs
using RCScustomer.DAL;
using RCScustomer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace RCScustomer.Controllers
{
    public class JobEstimateController : Controller
    {
        // GET: JobEstimate
        private RCSdbEntities db = new RCSdbEntities();
        private ManageJobEstimates manage = new ManageJobEstimates();
        // GET: JobEstimate
        public ActionResult Index()
        {
            if (GlobalClass.SystemSession)
            {
               List<EstimateClass> model = new List<EstimateClass>();
                
                model = manage.GetAllJobEstimatesForThisCustomer();
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
        public ActionResult ViewEstimates(Guid id)
        {
            if (GlobalClass.SystemSession)
            {
                PreviewSalesInvoiceClass model = new PreviewSalesInvoiceClass();
                model.InvoiceDetailList = new List<JobSalesInvoiceClass>();
                model = manage.FillSalesInvoiceOrEstimateDataForPreview(id);
                ViewBag.mess = "";
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
        [HttpPost]
        public ActionResult ViewEstimates(PreviewSalesInvoiceClass model)
        {
            if (GlobalClass.SystemSession)
            {

                ViewBag.mess = "";
                if (ModelState.IsValid)
                {
                    DataReturn data = new DataReturn();
                    data = manage.SaveEstimateRemarks(model);
                    ViewBag.mess = data.mess;                   
                    model.EstimateObj.IsNew = false;
                }
                PreviewSalesInvoiceClass obj = new PreviewSalesInvoiceClass();
                obj.InvoiceDetailList = new List<JobSalesInvoiceClass>();
                obj = manage.FillSalesEstimateDataForPreview(model.EstimateObj.InvoiceKey);
                
                obj.EstimateObj = new EstimateClass();
                obj.EstimateObj.InvoiceKey = model.EstimateObj.InvoiceKey;
                obj.EstimateObj.Pkey = model.EstimateObj.Pkey;
                obj.EstimateObj.Remark = model.EstimateObj.Remark;
                obj.EstimateObj.ViewRemark = model.EstimateObj.Remark;
                obj.EstimateStatus = model.EstimateStatus;
                obj.EstimateObj.IsNew = model.EstimateObj.IsNew;
                obj.EstimateObj.JobKey = model.EstimateObj.JobKey;
                model = obj;
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RCScustomer/Views/JobEstimate/Index.cshtml
@model IEnumerable<RCScustomer.Models.EstimateClass>

@{
    ViewBag.Title = "Estimates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $('#example4').dataTable();
    });
</script>

@section PageHeader{

   Estimates Received

}
<div class="row">



    <table id="example4" class="table table-bordered">
        <thead>
            <tr>


                <th>Service Location</th>
                <th>Trade</th>
                <th>Customer Job Name</th>
                <th>Status</th>
                <th>Entry Date</th>
                <th>Invoice No</th>
                <th>View</th>
               
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>


                    <td>
                        @Html.DisplayFor(modelItem => item.LocationName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TradeName)
                    </td>
                    <td>
                        <a href="@Url.Action("ViewJobDetails", "JobDetails", new { id = item.JobKey })">@Html.DisplayFor(modelItem => item.Jobname)</a>
                 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SalesStatusName)
                    </td>
                   
                    <td>
                        @string.Format("{0:D}",item.EntryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InvoiceNo)
                    </td>

                    <td>
                       

                        @Html.ActionLink("View Estimates", "ViewEstimates", "JobEstimate", new { id = item.InvoiceKey }, null)
                    </td>


                </tr>
                            }
        </tbody>
    </table>


</div>

RCScustomer/Views/JobEstimate/ViewEstimates.cshtml
@model RCScustomer.Models.PreviewSalesInvoiceClass

@{
    ViewBag.Title = "Estimates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using RCScustomer.Models
<script type="text/javascript">
    $(function () {
        $('#example4').dataTable();
    });

    $(document).ready(function (e) {
        $("#NoteDiv").hide();
      
        $("#Approved").click(function (event) {
            $("#Resubmit").hide();
            $("#Decline").hide();
           
            $("#NoteDiv").show();
            $("#EstimateStatus").val("1");
            if (($.trim($('#Remark').val()) == '')) {
                alert("RCS has received their accepted estimate and will proceed accordingly. Please enter some Note.");
                event.preventDefault();
                $("#NoteDiv").show();
            }
            $("#flag").val("2");
        });
        $("#Decline").click(function (event) {
            
            $("#NoteDiv").show();
            $("#Resubmit").hide();
            $("#Approved").hide();
            $("#EstimateStatus").val("2");
            if (($.trim($('#Remark').val()) == '')) {
                event.preventDefault();
                alert("RCS has received your request to reject this estimate. Would you like for RCS to re-visit this estimate, please leave feedback of your concerns. Note is Compulsory!");
              
            }
            $("#flag").val("2");
        });
        $("#Resubmit").click(function (event) {
            $("#NoteDiv").show();
            $("#Decline").hide();
            $("#Approved").hide();
            $("#EstimateStatus").val("3");
            if(($.trim($('#Remark').val()) == '')) {
                event.preventDefault();
                alert("RCS has received your request to resubmit this estimate, Please provide specific feedback of what you are wanting changed about this estimate. Note is Compulsory!");

            }
            $("#flag").val("2");
        });

    });

</script>


    <div class="row">
        <div class="col-xs-12">


            <div class="row invoice-info">
                <div class="col-sm-5 invoice-col">
                   
                </div>
                <div class="col-sm-2 invoice-col">
                    &nbsp;
                </div>
                <div class="col-sm-5 invoice-col">
                    <br /><br />
                    <h4>@Html.DisplayFor(m => m.Estimate_status)</h4>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-11">


            <div class="row invoice-info">

                <div class="col-sm-6 invoice-col">
                    @{
                        if (Model.config.IsServiceLicationVisible == false)
                        {
                            <label class="Underline">SERVICE LOCATION</label><br />
                            @Html.DisplayFor(m => m.ServiceLocation.Lname)<br />
                            @Html.DisplayFor(m => m.ServiceLocation.Address)<br />
                            @Html.DisplayFor(m => m.ServiceLocation.ZIPcode)<br />
                            @Html.DisplayFor(m => m.LocationCity)<br />
                            @Html.DisplayFor(m => m.locationState)<br />
                        }
                    }
                    @{
                        if (Model.config.IsCustomerPOVisible == false)
                        {
                            <label class="Underline">CUSTOMER PO : </label>
                            @Html.DisplayFor(m => m.Customer.ZIPcode)
                        }
                    }


                </div>
              

            </div>
        </div>
    </div>


    <div class="row">

        <div class="col-xs-11">
            <table class="table table-bordered">

                <thead><tr><th>DESCRIPTION</th><th>QTY</th><th>COST</th><th>TOTAL</th></tr></thead>
                <tbody>
                    @{
                        if (Model.config.IsInvoiceDetailVisible == false)
                        {
                            foreach (var item in Model.InvoiceDetailList)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(m => item.ChargeTypeName)    <label>  </label>@Html.DisplayFor(m => item.Description)</td>
                                    <td>@Html.DisplayFor(m => item.Qty) </td>
                                    <td>@Html.DisplayFor(m => item.Rate)</td>
                                    <td>@Html.DisplayFor(m => item.Amt) </td>

                                </tr>
                            }
                        }
                    }
                    <tr>
                        <td colspan="2">@MvcHtmlString.Create(Model.Remark)</td>
                        <td><label>TOTAL</label></td>
                        <td><label>$ </label> @Html.DisplayFor(m => m.Total)</td>
                    </tr>
                </tbody>

            </table>
        </div>
    </div>

    

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h3>@ViewBag.mess</h3>

    <input type="hidden"id="flag" name="flag" value="1" />
    @Html.HiddenFor(m => m.EstimateObj.InvoiceKey)
    @Html.HiddenFor(m => m.EstimateObj.Pkey)
    @Html.HiddenFor(m => m.EstimateObj.JobKey)
    @Html.HiddenFor(m => m.EstimateObj.IsNew)
    <div class="row">
        <div class="panel panel-default ">
            <div class="panel-heading">Respond</div>
            <div class="panel-body">
                <div class="form-horizontal">
                  @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-md-12">

                        <div class="form-group" id="NoteDiv">
                            @Html.LabelFor(model => model.Remark,"Note", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                              
                                @Html.TextAreaFor(model => model.EstimateObj.Remark, 5, 12, new { id = "Remark", @class = "form-control" })
                              
                                @Html.ValidationMessageFor(model => model.EstimateObj.Remark, "", new { @class = "text-danger" })

                                @Html.HiddenFor(model => model.EstimateStatus, new { id= "EstimateStatus" })
                            </div>
                        </div>   
                        <div class="form-group">
                          
                            <div class="col-md-7">
                                @*@Html.RadioButtonFor(model => model.EstimateStatus,1)  Accept Estimate As Approved<br />
                                @Html.RadioButtonFor(model => model.EstimateStatus, 2) Decline Estimate <br />
                                @Html.RadioButtonFor(model => model.EstimateStatus, 3) Resubmit Estimates<br />
                                @Html.ValidationMessageFor(model => model.EstimateStatus, "", new { @class = "text-danger" })*@

                                @{
                                    if (Model.EstimateObj.IsNew == false)
                                    {
                                        <label>Response : </label><br />
                                        @Html.DisplayFor(model => model.EstimateObj.ViewRemark)
                                    }
                                }         
                            </div>
                        </div>            
                     </div>                    
                </div>
            </div>
            <div class="panel-footer"> 
                @{
                    if (Model.EstimateObj.IsNew == true)
                    {
                        <input type="submit" name="Approved" id="Approved" value="Accept Estimate As Approved" class="btn btn-primary" /> <label>||</label>
                        <input type="submit" name="Decline" id="Decline" value="Decline Estimate" class="btn btn-primary" /> <label>||</label>
                        <input type="submit" name="Resubmit" id="Resubmit" value="Resubmit Estimates" class="btn btn-primary" /> 
                    }
                }             
                
                @Html.ActionLink("GO Back", "Index", "JobEstimate", null, null)||


                @Html.ActionLink("Ask YOUR RCS REP A QUESTION ABOUT THIS ESTIMATE","NotesandActivity", "JobDetails", new { id = Model.EstimateObj.JobKey }, null)
                </div>
        </div>
    </div>


                    }