RCScustomer/Models/JobRequest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCScustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobRequest()
        {
            this.JobRequestAttachments = new HashSet<JobRequestAttachments>();
        }
    
        public System.Guid RequestKey { get; set; }
        public Nullable<System.Guid> LocationKey { get; set; }
        public Nullable<System.Guid> CustomerKey { get; set; }
        public Nullable<System.Guid> LocationContactKey { get; set; }
        public Nullable<System.Guid> TradeKey { get; set; }
        public Nullable<System.Guid> JobPriorityKey { get; set; }
        public string ServiceNeeded { get; set; }
        public Nullable<decimal> DNEamount { get; set; }
        public string SpecialNote { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string ServiceByTime { get; set; }
        public string SVCLocationContact { get; set; }
        public string SvcLocationContactPhone { get; set; }
        public Nullable<System.DateTime> EntryDatetime { get; set; }
        public Nullable<bool> IsRequest { get; set; }
        public Nullable<System.Guid> CContactKey { get; set; }
        public Nullable<bool> Isviewed { get; set; }
        public string ServiceNeededByOrOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Location Location { get; set; }
        public virtual LocationContact LocationContact { get; set; }
        public virtual Trade Trade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequestAttachments> JobRequestAttachments { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
    }
}

RCScustomer/Controllers/JobRequestController.cs
using RCScustomer.DAL;
using RCScustomer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace RCScustomer.Controllers
{
    public class JobRequestController : Controller
    {
        private RCSdbEntities db = new RCSdbEntities();
        private JobRequestSetup manage = new JobRequestSetup();
        // GET: JobRequest
        public ActionResult Index()
        {
            if (GlobalClass.SystemSession)
            {
                DashBoardJobRequest model = new DashBoardJobRequest();
                model.JobRequestList = new List<JobRequestObject>();
                model.JobRequestList = manage.GetAllJobRequestForThisCustomer();
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
        public ActionResult Details(Guid id)
        {
            if (GlobalClass.SystemSession)
            {
                JobRequestObject model = new JobRequestObject();
              
                model = manage.GetJobrequestDetails(id);
                ViewBag.JobPriorityKey = new SelectList(db.JobType.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName",model.JobPriorityKey);
             
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
       

        public ActionResult Create()
        {
            if (GlobalClass.SystemSession)
            {
                Guid PriorityKey = Guid.Parse("98611896-68b9-42ae-b429-644069ae8587");
                ViewBag.JobPriorityKey = new SelectList(db.JobType.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName", PriorityKey);
                ViewBag.TradeKey = new SelectList(db.Trade.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName");
                return View();
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JobRequestObject model,string Save, string Close,string Next,string SaveCloseTab1,string Cancel, string Cancel1)
        {


            if (GlobalClass.SystemSession)
            {

                if (!string.IsNullOrEmpty(Cancel)) return RedirectToAction("Index", "Home");
                if (!string.IsNullOrEmpty(Cancel1)) return RedirectToAction("Index", "Home");
                if (ModelState.IsValid)
                {
                    
                   
                        DataReturn data = manage.SaveMainData(model);
                        ViewBag.mess = data.mess;
                        if (data.flag == 1)
                        {
                            if (!string.IsNullOrEmpty(Save)) return RedirectToAction("EditJobRequest", new { id = data.key });
                            else if (!string.IsNullOrEmpty(SaveCloseTab1)) return RedirectToAction("EditJobRequest", new { id = data.key });
                            else if (!string.IsNullOrEmpty(Next)) return RedirectToAction("Index", "JobRequestFile", new { id = data.key });
                            else return RedirectToAction("Index", "Home");
                        }
                    
                }
                ViewBag.JobPriorityKey = new SelectList(db.JobType.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName",model.JobPriorityKey);
                ViewBag.TradeKey = new SelectList(db.Trade.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName",model.TradeKey);
                return View(model);

            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }



        public ActionResult EditJobRequest( Guid id)
        {
            if (GlobalClass.SystemSession)
            {
               
                JobRequestObject model = new JobRequestObject();
                model = manage.GetJobrequestDetails(id);
                ViewBag.JobPriorityKey = new SelectList(db.JobType.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName",model.JobPriorityKey);
                ViewBag.TradeKey = new SelectList(db.Trade.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName", model.TradeKey);
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditJobRequest(JobRequestObject model, string Save, string Close)
        {
            if (GlobalClass.SystemSession)
            {
                if (ModelState.IsValid)
                {
                    DataReturn data = manage.UpdateMainData(model);
                    ViewBag.mess = data.mess;
                    if (data.flag == 1)
                        if (!string.IsNullOrEmpty(Save)) model = manage.GetJobrequestDetails(model.RequestKey);
                        else return RedirectToAction("Index", "Home");
                   
                }
                ViewBag.JobPriorityKey = new SelectList(db.JobType.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName",model.JobPriorityKey);
                ViewBag.TradeKey = new SelectList(db.Trade.Where(m => m.IsDelete == false).OrderBy(m => m.TName), "ID", "TName", model.TradeKey);
                return View(model);
               
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }

        public ActionResult Delete(Guid id)
        {
            if (GlobalClass.SystemSession)
            {
                
                    var Jobrq = db.JobRequestAttachments.Where(f => f.RequestKey == id).ToList();
                db.JobRequestAttachments.RemoveRange(Jobrq);
                db.SaveChanges();
                db = new RCSdbEntities();
                JobRequest obj = db.JobRequest.Find(id);
                    db.JobRequest.Remove(obj);
                    db.SaveChanges();
              
                return RedirectToAction("Index");
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

RCScustomer/Views/JobRequest/Details.cshtml
@model RCScustomer.Models.JobRequestObject


@{
    ViewBag.Title = "Job";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts
{
    <script src="~/Scripts/scStateCity.js"></script>
}

@section PageHeader{

    Jobs Request Details

}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h3>@ViewBag.mess</h3>

    <div class="row">
        <div class="panel panel-default ">
            <div class="panel-heading">General Info</div>
            <div class="panel-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.RequestKey, new { id = "JobKey" })
                    @Html.HiddenFor(model => model.CustomerKey, new { id = "CustomerKey" })
                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.LocationName, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.LocationName, new { htmlAttributes = new { id = "LocationName", @class = "form-control", disabled = "disabled" } })
                                @Html.HiddenFor(model => model.LocationKey, new { id = "LocationKey" })
                                @Html.ValidationMessageFor(model => model.LocationKey, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.LocationContactName, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { id = "ContactName", @class = "form-control", disabled = "disabled" } })
                              
                            </div>
                        </div>
                    </div>


                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.LocationContactAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LocationContactAddress, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.LocationContactAddress, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.LocationContactCityName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LocationContactCityName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.LocationContactCityName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.LocationContactStateName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LocationContactStateName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.LocationContactStateName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.LocationContactZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LocationContactZipCode, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.LocationContactZipCode, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>

                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.TradeName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TradeName, new { htmlAttributes = new { id = "TradeName", @class = "form-control", disabled = "disabled" } })
                                @Html.HiddenFor(model => model.TradeKey, new { id = "TradeKey" })
                                @Html.ValidationMessageFor(model => model.TradeKey, "", new { @class = "text-danger" })

                            </div>
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.JobPriorityKey, "Job Type", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("JobPriorityKey", null, htmlAttributes: new { @required = "required", @class = "form-control", disabled = "disabled" })
                                @Html.ValidationMessageFor(model => model.JobPriorityKey, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ServiceNeeded, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ServiceNeeded, new { htmlAttributes = new { id = "ServiceNeeded", @class = "form-control", disabled = "disabled" } })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="panel panel-default ">
            <div class="panel-heading">Optional Info</div>
            <div class="panel-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.DNEamount, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.DNEamount, new { htmlAttributes = new { id = "DNEamount", @class = "form-control", disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.DisplayFor(model => model.ServiceNeededByOrOn)
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.ServiceDate, new { htmlAttributes = new { id = "ServiceDate", @class = "form-control", disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ServiceByTime, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.ServiceByTime, new { htmlAttributes = new { id = "ServiceByTime", @class = "form-control", disabled = "disabled" } })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.SpecialNote, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.SpecialNote, new { htmlAttributes = new { id = "SpecialNote", @class = "form-control", disabled = "disabled" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SVCLocationContact, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.SVCLocationContact, new { htmlAttributes = new { id = "SVCLocationContact", @class = "form-control", disabled = "disabled" } })
                            </div>

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SvcLocationContactPhone, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.SvcLocationContactPhone, new { htmlAttributes = new { id = "SvcLocationContactPhone", @class = "form-control", disabled = "disabled" } })
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

            <div class="row">
                <div class="panel panel-default ">
                    <div class="panel-heading">FILE AND ATTACHMENT</div>
                    <div class="panel-body">

                        <table id="example2" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Document Type</th>
                                    <th>View Files</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.JobRequestAttachmentsObjectList)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DocumentName)
                                        </td>

                                        <td>
                                            @Html.ActionLink("View File", "GetJobRequestFileAttachement", "ShowImage", new { id = item.PKey }, new { target = "_blank" })
                                        </td>

                                    </tr>
                                }

                            </tbody>
                        </table>


                    </div>
                     
                </div>
            </div>
}

RCScustomer/Views/JobRequest/Index.cshtml
@model RCScustomer.Models.DashBoardJobRequest
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $('#example4').dataTable();
    });
</script>

@section PageHeader{

    My Jobs Request

}
<div class="row">



    <table id="example4" class="table table-bordered">
        <thead>
            <tr>

                 
                <th>Location Name</th>
                <th>Location Contact Name</th>
                <th> Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Trade</th>
                <th>Job Priority</th>
               
              
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.JobRequestList)
            {
                <tr>

                    
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationContactName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationContactAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationContactCityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationContactStateName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocationContactZipCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TradeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobPriority)
                    </td>                  
                


                    <td>
                        @{
                            if (item.IsRequest == true)
                            {
                                @Html.ActionLink("Edit", "EditJobRequest", "JobRequest", new { id = item.RequestKey }, null) <label>||</label>
                                @Html.ActionLink("Delete", "Delete", "JobRequest", new { id = item.RequestKey }, new { onclick = "return confirm('Are you sure you want to Remove this?')" })<label>||</label>

                            }
                        }
                       
                        @Html.ActionLink("Details", "Details", "JobRequest", new { id = item.RequestKey }, null)
                    </td>


                </tr>
            }
        </tbody>
    </table>


</div>