RCScustomer/Controllers/JobRequestFileController.cs
using RCScustomer.DAL;
using RCScustomer.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RCScustomer.Controllers
{
    public class JobRequestFileController : Controller
    {
        private RCSdbEntities db = new RCSdbEntities();
        JobRequestSetup setup = new JobRequestSetup();
        // GET: JobRequestFile
        public ActionResult Index(Guid id)
        {
            if (GlobalClass.SystemSession)
            {
                JobRequestAttachmentMain model = new JobRequestAttachmentMain();
             
                ViewBag.mess = " ";

                model = setup.GetJobFileAttachmentObjects(id);

                ViewBag.DocumentTypeKey = new SelectList(db.DocumentType.Where(m => m.DocumentForID == 6 && m.IsDelete == false && m.CompanyKey == GlobalClass.Company.CompanyKey).OrderBy(m => m.TName), "ID", "TName");

                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file, JobRequestAttachmentMain model)
        {
            if (GlobalClass.SystemSession)
            {
                ViewBag.mess = "";
                model.fileObj = new JobRequestAttachmentsObject();
                model.fileObj.RequestKey = model.RequestObj.RequestKey;
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        byte[] data = null;
                        using (Stream inputStream = file.InputStream)
                        {
                            MemoryStream memoryStream = inputStream as MemoryStream;
                            if (memoryStream == null)
                            {
                                memoryStream = new MemoryStream();
                                inputStream.CopyTo(memoryStream);
                            }
                            data = memoryStream.ToArray();
                        }
                        model.fileObj.FileType = file.ContentType;
                        model.fileObj.Filename = file.FileName;
                        model.fileObj.DocFile = data;
                        DataReturn dt = setup.SaveAttachmentInRequest(model);
                        ViewBag.mess = dt.mess;
                    }
                }


                model = setup.GetJobFileAttachmentObjects(model.RequestObj.RequestKey);

                ViewBag.DocumentTypeKey = new SelectList(db.DocumentType.Where(m => m.DocumentForID == 6 && m.IsDelete == false && m.CompanyKey == GlobalClass.Company.CompanyKey).OrderBy(m => m.TName), "ID", "TName");

                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
    }
}

RCScustomer/Views/JobRequestFile/Index.cshtml
@model RCScustomer.Models.JobRequestAttachmentMain

@{
    ViewBag.Title = "Job Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
$(document).ready(function(){
    $("#fileid").on('change',function(){
        alert("FILE IS UPLOADED, PLEASE CHOOSE: “SAVE FILE NOW");
    });
});
</script>
@using (Html.BeginForm("Index", "JobRequestFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <h3>@ViewBag.mess</h3>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-pills">
                    <li>                       
                        <a href="@Url.Action("EditJobRequest", "JobRequest", new { id = Model.RequestObj.RequestKey })">Main</a>
                    </li>
                    <li>
                        <a href="@Url.Action("EditJobRequest", "JobRequest", new { id = Model.RequestObj.RequestKey })">Optional Information</a>
                    </li>
                    <li class="active">
                        <a href="#2a" data-toggle="pill">Files and attachment</a>
                     
                    </li>

                </ul>
            </div>
        </div>
    </div>


    <div class="tab-content">

        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">Job Request File & Attachements</div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.RequestObj.RequestKey, new { id = "RequestKey" })
                     

                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.DocumentTypeKey,"Documenbt Type", htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.DropDownList("DocumentTypeKey", null, htmlAttributes: new { @required = "required", id = "DocumentTypeKey", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.DocumentTypeKey, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.DocumentTypeKey, "Upload File", htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-9">
                                    <input type="file" name="file" id="fileid" />
                                </div>
                            </div>

                          
                        </div>

                    </div>
                </div>

                <div class="panel-footer">
                    <input type="submit" name="Save" id="Save" value="SAVE FILE NOW" class="btn btn-primary" />
                    @Html.ActionLink("Refresh", "Index", "JobRequestFile", new { id = Model.RequestObj.RequestKey }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel panel-warning">
                <div class="panel-heading"><center><h4>Files Under this Request</h4></center></div>
                <table id="example2" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Document Type</th>
                            <th>Document Name</th>
                          

                            <th>View Files</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.JobRequestAttachmentsList)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DocumentName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Filename)
                                </td>
                               
                                <td>
                                    @Html.ActionLink("View File", "GetJobRequestFileAttachement", "ShowImage", new { id = item.PKey }, new { target = "_blank" })
                                </td>

                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>

    </div>
}