RCScustomer/Controllers/JobDetailsController.cs
using RCScustomer.DAL;
using RCScustomer.Models;
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RCScustomer.ExcelConvertor;
using System.IO;

namespace RCScustomer.Controllers
{
    public class JobDetailsController : Controller
    {

        private RCSdbEntities db = new RCSdbEntities();

        private ManageJobSetup manage = new ManageJobSetup();
        private ExcelUtility excelutility = new ExcelUtility();
        // GET: JobDetails
        public ActionResult DownloadCustomerCommunication(Guid id)
        {
            List<RCSExcel> mainlist = new List<RCSExcel>();
            Job job = db.Job.Find(id);

            mainlist = manage.CustomerCommunicationForDownload(id);
            DataTable dt = excelutility.ConvertToDataTable(mainlist);
          
            FileClass file = new FileClass();
            file = excelutility.WriteDataTableToExcel(dt, job.JobName, "Customer Communication");
            if (file.FileContent != null)
                return File(file.FileContent, "application/vnd.ms-excel");
            else
            {
                ImageFile faoimagefile = db.ImageFile.Single(f => f.ImageFileKey == 1);
                return File(faoimagefile.FileContent, faoimagefile.FileType);
            }
        }
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ViewJobDetails(Guid id)
        {


            if (GlobalClass.SystemSession)
            {
               
                JobClass model = new JobClass();
                model = manage.FillMainJob(id);
                ViewBag.mess = "MY RCS JOB "+model.JobName;
                ViewBag.mesg = "THE FOLLOWING ARE READONLY INFORMATION PERTAINING TO THE JOB - " + model.JobName;
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }

        public ActionResult NotesandActivity(Guid id)
        {
            if (GlobalClass.SystemSession)
            {
                ViewBag.mess = " ";
               
                RCSMessegeClass model = new RCSMessegeClass();             
                model = manage.LoadCustomerMessegingData(id);
                ViewBag.mess = "MY RCS JOB " + model.Job.JobName+" - Activities.";
                ViewBag.title = "Activities Related to JOB - " + model.Job.JobName;
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NotesandActivity(RCSMessegeClass model, string save, string savenEmail)
        {
            if (GlobalClass.SystemSession)
            {
                ViewBag.mess = "MY RCS JOB " + model.Job.JobName + " - Activities.";
                ViewBag.title = "Activities Related to JOB - " + model.Job.JobName;

                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(save))
                    {
                        if (model.mainObj.PKey == null || model.mainObj.PKey == Guid.Empty)
                        {
                            DataReturn data = manage.SaveCustomermessegingData(model);
                            ViewBag.mess = data.mess;
                            model = manage.LoadCustomerMessegingData((Guid)model.mainObj.JobKey);
                        }
                        else
                        {
                            DataReturn data = manage.UpdateCustomermessegingData(model);
                            ViewBag.mess = data.mess;
                            model = manage.LoadCustomerMessegingData((Guid)model.mainObj.JobKey);
                        }
                    }
                    if (!string.IsNullOrEmpty(savenEmail))
                    {
                        //DataReturn data = manage.SaveCustomermessegingData(model);
                        //CustomerMesseging lastObj = db.CustomerMesseging.Find(data.key);
                        //bool f = Mail.SendEmailToCustomerForJobUpdate(lastObj);
                        //ViewBag.mess = data.mess;
                        //model = manage.LoadCustomerMessegingData((Guid)model.mainObj.JobKey);
                    }

                }

                model = manage.LoadCustomerMessegingData((Guid)model.mainObj.JobKey);
                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }


        public ActionResult FilesandAttachments(Guid id)
        {
            if (GlobalClass.SystemSession)
            {
                JobFileClass model = new JobFileClass();
                Job job = db.Job.Find(id);

                model = manage.GetJobFileAttachments(id);
                model.JobKey = id;
                model.JobName = job.JobName;
                ViewBag.mess = " ";

                ViewBag.DocumentTypeKey = new SelectList(db.DocumentType.Where(m => m.DocumentForID == 6 && m.IsDelete == false && m.CompanyKey == GlobalClass.Company.CompanyKey).OrderBy(m => m.TName), "ID", "TName");

                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
        [HttpPost]
        public ActionResult FilesandAttachments(HttpPostedFileBase file, JobFileClass model)
        {
            if (GlobalClass.SystemSession)
            {
                ViewBag.mess = "";
                Job job = db.Job.Find(model.JobKey);
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        byte[] data = null;
                        using (Stream inputStream = file.InputStream)
                        {
                            MemoryStream memoryStream = inputStream as MemoryStream;
                            if (memoryStream == null)
                            {
                                memoryStream = new MemoryStream();
                                inputStream.CopyTo(memoryStream);
                            }
                            data = memoryStream.ToArray();
                        }
                        model.FileType = file.ContentType;
                        model.Title = file.FileName;
                        model.FileContent = data;
                        DataReturn dt = manage.SaveAttachmentInJobFile(model);
                        ViewBag.mess = dt.mess;
                    }
                }


                model = new JobFileClass();
                model = manage.GetJobFileAttachments((Guid)job.JobKey);
                model.JobKey = job.JobKey;
                model.JobName = job.JobName;

                ViewBag.DocumentTypeKey = new SelectList(db.DocumentType.Where(m => m.DocumentForID == 6 && m.IsDelete == false && m.CompanyKey == GlobalClass.Company.CompanyKey).OrderBy(m => m.TName), "ID", "TName");

                return View(model);
            }
            else
            {
                Exception e = new Exception("Sorry, your Session has Expired");
                return View("Error", new HandleErrorInfo(e, "Home", "Logout"));
            }
        }
    }
}

RCScustomer/Views/JobDetails/FilesandAttachments.cshtml
@model RCScustomer.Models.JobFileClass
@{
    ViewBag.Title = "FilesAndAttachments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {

        $("#DocumentTypeKey").val("");
        $("#Comment").val("");


    });
</script>
@using (Html.BeginForm("FilesandAttachments", "JobDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <h3>@ViewBag.mess</h3>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-pills">
                    <li>
                        <a href="@Url.Action("ViewJobDetails", "JobDetails",new { id=Model.JobKey})">Job Info</a>
                    </li>
                    <li>
                        <a href="@Url.Action("NotesandActivity", "JobDetails",new { id=Model.JobKey})">Notes and Activity</a>
                    </li>
                    <li class="active">
                        <a href="#1a" data-toggle="pill">Attach Documents</a>
                    </li>


                </ul>
            </div>
        </div>
    </div>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="1a">
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">@Html.DisplayFor(model => model.JobName) >> Job File & Attachements</div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.JobKey, new { id = "JobKey" })
                            @Html.HiddenFor(model => model.JobName, new { id = "JobName" })

                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DocumentTypeKey, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.DropDownList("DocumentTypeKey", null, htmlAttributes: new { @required = "required", id = "DocumentTypeKey", @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.DocumentTypeKey, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <input type="file" name="file" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { id = "Comment", @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="panel-footer">
                        <input type="submit" name="Save" id="Save" value="Save this File" class="btn btn-primary" />
                        @Html.ActionLink("Refresh", "Index", "MgtJobFile", new { id = Model.JobKey }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel panel-warning">
                    <div class="panel-heading"><center><h4>Files Under this Job</h4></center></div>
                    <table id="example2" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Document Type</th>
                                <th>Document Name</th>
                                <th>Comment</th>

                                <th>View Files</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Joblist)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DocumentTypeName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Comment)
                                    </td>
                                    <td>
                                        @Html.ActionLink("View File", "GetJobFileAttachement", "ShowImage", new { id = item.FileKey }, new { target = "_blank" })
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>



        </div>
    </div>
                                            }

RCScustomer/Views/JobDetails/NotesandActivity.cshtml
@model RCScustomer.Models.RCSMessegeClass
@{
    ViewBag.Title = "NotesAndActivity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/datetimepicker-master/build/jquery.datetimepicker.min.css" rel="stylesheet" />
<script src="~/Content/datetimepicker-master/build/jquery.datetimepicker.full.js"></script>
<script type="text/javascript">

    $(function () {
        $('#AddedOn').datetimepicker({
            step: 5
        });
    });

    $(document).ready(function (e) {

        $('#Comment').val("");
        $('#AddedOn').val("");
        $('#savenEmail').show();
        $('#save').show();



        $(".discussion-comment").click(function (event) {
           // alert($(this).attr("discussioned"));
            //var k = $(this).attr("discussioned");
            //alert($(k).val());
            $('#PKey').val($(this).attr("discussion-id"));

            var w = "#PKey";

            var url = '@Url.Content("~/")' + "Utility/LoadCustomerMessege";
            $.getJSON(url, { SelectID: $(w).val() }, function (data) {

                $('#AddedOn').val(data["Title"]);
                $('#Comment').val(data["Comment"]);
                $('#savenEmail').hide();
                $('#save').hide();


            });


        });
    });
        $(function () {
            $('#example2').dataTable();
        });
       
</script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h3>@ViewBag.mess</h3>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-pills">
                    <li>
                        <a href="@Url.Action("ViewJobDetails", "JobDetails",new { id=Model.Job.JobKey})">Job Info</a>
                    </li>
                    <li class="active">
                        <a href="#1a" data-toggle="pill">Notes and Activity</a>
                    </li>
                    

                    <li>
                        <a href="@Url.Action("FilesandAttachments", "JobDetails",new { id=Model.Job.JobKey})">Attach Documents</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="1a">
            <div class="row">
                <div class="panel panel-default ">
                    <div class="panel-heading"><h3>@Html.DisplayFor(model => model.Job.JobName) >> @ViewBag.title</h3></div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.mainObj.PKey, new { id = "PKey" })
                            @Html.HiddenFor(model => model.mainObj.JobKey, new { id = "JobKey" })
                            @Html.HiddenFor(model => model.Job.JobName, new { id = "JobName" })
                            @Html.HiddenFor(model => model.VendorKey, new { id = "VendorKey" })

                            <div class="col-md-4">
                             
                                <div class="form-group">
                                    @Html.LabelFor(model => model.mainObj.AddedOn, htmlAttributes: new { @class = "control-label col-md-4" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.mainObj.AddedOn, new { htmlAttributes = new { id = "AddedOn", @class = "datepicker form-control" } })
                                        @Html.ValidationMessageFor(model => model.mainObj.AddedOn, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.mainObj.Comment, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.TextAreaFor(model => model.mainObj.Comment, 6, 70, new { id = "Comment", @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.mainObj.Comment, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="panel-footer">
                        @*<input type="submit" id="savenEmail" name="savenEmail" value="Add Activity & email" class="btn btn-primary" />*@
                        <input type="submit" id="save" name="save" value="Add Activity" class="btn btn-primary" />
                        <input type="submit" id="refresh" name="refresh" value="Refresh" class="btn btn-primary" />
                        <a href="@Url.Action("FilesandAttachments", "JobDetails",new { id=Model.Job.JobKey})" class="btn btn-primary" title="CHOOSE NEXT FOR ADDING ATTACHMENTS OR SAVE AND CLOSE TO SUBMIT NOW.">>>Next</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="panel panel-default ">
                    <div class="panel-heading">recent activity</div>
                    <table id="example2" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Date and Time</th>
                                <th>Done By</th>
                               

                                <th>Description</th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.mailList)
                            {
                                <tr>
                                  
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AddedOn)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Staffname) <label>-</label>
                                        @Html.DisplayFor(modelItem => item.Designation)
                                    </td>


                                    <td>
                                        @Html.DisplayFor(modelItem => item.Comment)
                                    </td>
                                    <td>
                                        @{
                                            if (item.IsAdmin == true)
                                            {

                                            }
                                            else
                                            {
                                                <a class="discussion-comment" discussion-bit="@item.IsAdmin" discussion-id="@item.PKey" href="#">View full description</a>
                                            }
                                        }
                                       
                                       
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>


                    <div class="panel-footer">
                        <a href="@Url.Action("DownloadCustomerCommunication", "JobDetails", new { id = Model.mainObj.JobKey })">Export to Excel</a>
                    </div>
                </div>

            </div>



        </div>
    </div>
}